[package]
name = "get-my-ip"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
external-ip = { optional = false, version = '4.1.0' }
tokio = { version = "1.33.0", features = ["full"] }
